version: '3.9'

services:
  financial-simulator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app/app
    restart: unless-stopped
